### ISSUE TITLE
Ricerca dei prodotti

### ISSUE THREAD

**Issue by FilippoFantinato** [NotOnlyStudents/Documentazione#104]
- [ ] Inserimento parole per ricerca
- [ ] Preme sull’azione di ricerca
- [ ] (inclusione del punto 2) Apertura vista PLP

**Comment by giuliat96** [comment]
L'apertura della PLP non è un'inclusione perché se l'utente cerca una cosa che non c'è viene visualizzato solo il messaggio di errore e non la PLP
