### ISSUE TITLE
Spostare "Visualizzazione PDP" dagli UC ai requisiti

### ISSUE THREAD

**Issue by FilippoFantinato** [NotOnlyStudents/Documentazione#112]

**Comment by giuliat96** [comment]
Cosa intendete?

**Comment by LeonardoTredese** [comment]
@FilippoFantinato  intendi eliminare l'uc e fare un requisito per ogni cosa che presente nella pdp?

**Comment by FilippoFantinato** [comment]
Si avevamo pensato così quando l'abbiamo aggiunto. Direi che è una cosa da chiedere a cardin

**Comment by giuliat96** [comment]
ok tipo "r1 nella pdp si deve visualizzare y" "r2 nella pdp si deve visualizzare z"?

**Comment by giuliat96** [comment]
> Si avevamo pensato così quando l'abbiamo aggiunto. Direi che è una cosa da chiedere a cardin

ok tipo "r1 nella pdp si deve visualizzare y" "r2 nella pdp si deve visualizzare z"?
