### ISSUE TITLE
Visualizzazione prodotti nel carrello

### ISSUE THREAD

**Issue by FilippoFantinato** [NotOnlyStudents/Documentazione#114]
- [ ] Visualizzare il prezzo totale, tasse ed eventuali sconti.
- [ ] Eliminazione di un prodotto dal carrello.
- [ ] Modifica della quantità di un prodotto già aggiunto nel carrello.
- [ ] Apertura della PDP di un prodotto premendo sull’azione specifica.

**Comment by giuliat96** [comment]
Ste cose ci sono già come pensavate di modificarle?
