### ISSUE TITLE
Checkout

### ISSUE THREAD

**Issue by FilippoFantinato** [NotOnlyStudents/Documentazione#117]
- [ ] Selezione indirizzo di spedizione
- [ ] Selezione della carta
- [ ] Conferma di pagamento

**Comment by giuliat96** [comment]
Avete messo selezione indirizzo di spedizione e carta, ma uno potrebbe voler inserirne di nuovi quindi va messa come opzione no?

**Comment by LeonardoTredese** [comment]
Si può aggiungere per seguire la linea di funzionamento amazon, vengono 2 uc in più

**Comment by giuliat96** [comment]
> Si può aggiungere per seguire la linea di funzionamento amazon, vengono 2 uc in più

uc1 in cui seleziona le due cose e uc2 in cui le inserisce?

**Comment by giuliat96** [comment]
> no i due in più sono uno per l'inserimento della carta e uno per l'inserimento dell'indirizzo, oltre a quelli già presenti per la selezione

In UC - Checkout:
- uc1 selezione carta
-  uc2 selezione indirizzo
-  uc3 inserimento carta
- uc4 inserimento indirizzo
così giusto?
