### ISSUE TITLE
Modifica carta di pagamento

### ISSUE THREAD

**Issue by FilippoFantinato** [NotOnlyStudents/Documentazione#123]

**Comment by DavideVarotto** [comment]
Ho un dubbio, non è inutile questo UC, in quanto i dati di una carta non possono essere mai modificati, o si imposta una carta nuova o la si elimina

**Comment by LeonardoTredese** [comment]
Ci sta come osservazione, ma se uno percaso sbaglia ad inserire la data di scadenza non può modificarla?
