### ISSUE TITLE
Modifica della quantità del prodotto da aggiungere al carrello

### ISSUE THREAD

**Issue by FilippoFantinato** [NotOnlyStudents/Documentazione#165]

**Comment by giuliat96** [comment]
Esiste già un "modifica della quantità del prodotto" che è una fusione tra "devo ancora inserire il prodotto nel carrello" e "il prodotto è già inserito" con questa issue volevate dividere in due casi o pensavate a altro?

**Comment by LeonardoTredese** [comment]
> Esiste già un "modifica della quantità del prodotto" che è una fusione tra "devo ancora inserire il prodotto nel carrello" e "il prodotto è già inserito" con questa issue volevate dividere in due casi o pensavate a altro?

Si esatto, dividere in due casi
