### ISSUE TITLE
UC3 Come funzionalità e non implementazione

### ISSUE THREAD

**Issue by LeonardoTredese** [NotOnlyStudents/Documentazione#71]
Tullio: "UC3 non rappresenta una funzionalità, ma è già calato in una possibile  implementazione che prevede l’uso di “menù”. I sotto-casi individuati soffrono del medesimo problema."

**Comment by FilippoFantinato** [comment]
- [ ] UC3
- [ ] UC3.1 e sotto casi
- [ ] UC3.2 e sotto casi
